@ECHO OFF
echo Running DataToMongoMigrator by user : aruba\fall.abdoullaj ...
runas /netonly /user:aruba\fall.abdoullaj ""C:\git\devspa\notifications\build\notifications\src\Aruba.Notifications.DataToMongoMigrator\bin\Release\Aruba.Notifications.DataToMongoMigrator.exe""